* Linux basics for hackers
  This is my notes for the book on linux
** Getting started with VM
   Linux distro: Kali
   VMbox by oracle
** Basic bash CH1
   ~whoami~: tells you if you are the root user or the user you are
   ~sudo su~: used to enter root functionality, C-d to exit
*** Finding stuff
    ~locate~: used to find files throughout the entier file system, not perfect
    ~whereis~: return binarys location and man page location. Binaries are executables in linux
    ~which~: returns location of binary in PATH var. PATH holds dirs where the os looks for commandsyou enter
    ~find / -type f -name fileName~: / is dir to start, f is the type to find, and name is the name to fine. This returns all instances of this starting at the root 
   ~grep~: grep is helpful to filter out of other commands using piplining.
*** Modifying files and dir
    ~cat > somefile~ Redirects the output what you pust into the file. C-D to stop. >> for appending.
    ~rm -r directory~ recursivly removes everything in a dir
** Text manipulation
   Everything in linux is a text file, understanding how to manipulate configurations is important. 
*** Simple file viewing
    Cat, head, teal
    ~nl~ dysplayes file with number lines
*** Simple find and replace
    ~sed s/hello/Hello/g sometextFile.txt~ replaces all instances of hello with Hello.s/ means search and /g means global. 
